// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2OcooTzgTMsdYQo_gg9LJBff0qUnWCos',
    appId: '1:882282550117:web:aaf84974d50bb54d10078c',
    messagingSenderId: '882282550117',
    projectId: 'crime-dispose-2194f',
    authDomain: 'crime-dispose-2194f.firebaseapp.com',
    storageBucket: 'crime-dispose-2194f.appspot.com',
    measurementId: 'G-09BD75VZ5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL-sClRciVWm5VzmTotIm7Rtz9s0jJoOk',
    appId: '1:882282550117:android:80ddb788bff19ce410078c',
    messagingSenderId: '882282550117',
    projectId: 'crime-dispose-2194f',
    storageBucket: 'crime-dispose-2194f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9jI8iARKucPG4uvxzT-J60820q5qn3ME',
    appId: '1:882282550117:ios:3b44945f4797193810078c',
    messagingSenderId: '882282550117',
    projectId: 'crime-dispose-2194f',
    storageBucket: 'crime-dispose-2194f.appspot.com',
    iosBundleId: 'com.example.crimeDispose',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9jI8iARKucPG4uvxzT-J60820q5qn3ME',
    appId: '1:882282550117:ios:12411c6d5276cd2410078c',
    messagingSenderId: '882282550117',
    projectId: 'crime-dispose-2194f',
    storageBucket: 'crime-dispose-2194f.appspot.com',
    iosBundleId: 'com.example.crimeDispose.RunnerTests',
  );
}
